hostNetwork: false
jar:
  existingClaim: mlops-jars
  hostPath: ""
env:
  KAFKA_BOOTSTRAP_SERVERS: mlops-kafka-kafka-bootstrap.mlops-data.svc.cluster.local:9092
  PG_JDBC_URL: jdbc:postgresql://mlops-postgres-rw.mlops-data.svc.cluster.local:5432/mlops
  MINIO_S3_ENDPOINT: http://mlops-minio.mlops-data.svc.cluster.local:9000
  LAKE_WAREHOUSE: s3://mlops-lake
envSecretRef: events-lake-config
