apiVersion: v1
kind: Namespace
metadata:
  name: mlops-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-streaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
