architecture: standalone
image:
  repository: bitnamilegacy/redis
  tag: 8.0.3-debian-12-r3
  pullPolicy: IfNotPresent
auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretPasswordKey: redis-password
master:
  persistence:
    enabled: true
    storageClass: local-path
    size: 5Gi
service:
  type: ClusterIP
